#---------IntegrationServerFlows-----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
  namespace: integrations-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      containers:
      - name: integration-container
        image: ${AZURE_CONTAINER_REGISTRY}.azurecr.io/${CONTAINER_NAME}:latest
        ports:
        - containerPort: 5555

---
#-----------LoadBalancer---------------
apiVersion: v1
kind: Service
metadata:
  name: integration-service-lb
  namespace: integrations-ns
spec:
  type: LoadBalancer
  selector:
    app: integration-service
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555